# Generated by Django 4.0.1 on 2022-02-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
